#!/usr/bin/env sh

yabai -m config window_shadow off

#yabai -m config window_opacity_duration      0.0
# yabai -m config window_opacity on
# yabai -m config active_window_opacity        1
# yabai -m config normal_window_opacity        0.95
yabai -m config focus_follows_mouse autofocus

# Gap settings
yabai -m config layout                        bsp
yabai -m config top_padding                   40
yabai -m config bottom_padding                15
yabai -m config left_padding                  15
yabai -m config right_padding                 15
yabai -m config window_gap                    15

# yabai -m config top_padding                   0
# yabai -m config bottom_padding                0
# yabai -m config left_padding                  0
# yabai -m config right_padding                 0
# yabai -m config window_gap                    0



# Ignoring apps

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Tor Browser$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Folx$" manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^a.out$" manage=off

yabai -m rule --add label=emacs app=Emacs manage=on


# Don't tile desktop 1
#yabai -m config --space 1 layout float

